crowd_auth.server.*:
  type: config_entity
  label: 'Server config'
  mapping:
    id:
      type: string
      label: 'Machine name for this server configuration'
    label:
      type: label
      label: 'Name'
    uuid:
      type: string
    status:
      type: boolean
      label: 'Enabled'
    address:
      type: string
      label: 'Crowd Server address'
    app_login:
      type: string
      label: 'Crowd application login'
    app_pass:
      type: string
      label: 'Crowd application password'
    admin_login:
      type: string
      label: 'Administrator login'
    admin_pass:
      type: string
      label: 'Administrator password'
    crowd_cookie_name:
      type: string
      label: 'Crowd cookie name'
    weight:
      type: integer
      label: 'Weight'
    group_mapping:
      type: sequence
      sequence:
        type: mapping
        mapping:
          group_remote:
            type: string
            label: 'Crowd group'
          group_drupal:
            type: string
            label: 'Drupal group'